export const soundKeys = {
	key: "key",
	heart: "heart",
	bonus: "bonus",
	attack: "attack",
	wind: "wind",
	fire: "fire",
	ice: "ice",
	freeze: "freeze",
	plant: "plant",
	heal: "heal",
	destroy: "destroy",
	spirit: "spirit",
	holy: "holy",
	holyLoop: "holy-loop",
	rockDestroy: "rock-destroy",
	gameOver: "game-over",
	walk: "walk",
	roar: "roar",
	enemyWalk: "enemy-walk",
	iceCharge: "ice-charge",
	waterWalk: "water-walk",
	fireLoop: "fire-loop",
};

export const musicKeys = {
	mountainKingdom: "mountain-kingdom",
	iceKingdom: "ice-kingdom",
	fireKingdom: "fire-kingdom",
	spiritKingdom: "sprit-kingdom",
};
